apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-spring
  template:
    metadata:
      labels:
        name: hello-spring
    spec:
      containers:
        - name: hello-spring
          image: 192.168.1.111:8089/abc/hello-spring:v0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8899
---
apiVersion: v1
kind: Service
metadata:
  name: hello-spring-service-nodeport
spec:
  ports:
    - port: 8899
      targetPort: 8899
      protocol: TCP
      nodePort: 30080
  type: NodePort
  selector:
    name: hello-spring