apiVersion: apps/v1
kind: Deployment
metadata:
  name: nezha-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nezha-frontend
      version: v0.1
  template:
    metadata:
      labels:
        name: nezha-frontend
        version: v0.1
    spec:
      containers:
        - name: nginx
          image: 192.168.1.111:8089/nezha/nezha-frontend:v0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nezha-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  type: NodePort
  selector:
    name: nezha-frontend
    version: v0.1
